lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
    public_key_path: '%kernel.root_dir%/../var/jwt/public.pem'
    pass_phrase: ''
    token_ttl: 3600
    encoder:
        service:              lexik_jwt_authentication.encoder.default
        crypto_engine:        openssl
        signature_algorithm:  RS256
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:
            enabled: false
            name:    BEARER
        query_parameter:
            enabled: false
            name:    bearer
