nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps
            - ^/products
            - ^/users
            - ^/search
    documentation:
        info:
            title: BileMo API
            description: Welcome to the BileMo API documentation
            version: 1.0.0